baseURL = 'https://psygraberkoenig.com'
languageCode = 'de-de'
title = 'Dr. Heidi Graber-König'
theme = 'business'

disableKinds = ['sitemap']

[Params]
  subtitle = 'Psychotherapie in Hard, Vorarlberg'
  subtitle2 = 'Allgemeinmedizin und Komplementärmedizin'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
